-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER AS GENDER, COUNT(A.USER_ID) AS USERS
FROM (SELECT * FROM ONLINE_SALE GROUP BY USER_ID,DATE_FORMAT(SALES_DATE,"%Y-%m")) AS A, USER_INFO AS B
WHERE A.USER_ID = B.USER_ID AND B.GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR, MONTH, GENDER;

