
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY, SUM(A.TOTAL_SALES) AS TOTAL_SALSES 
FROM
(SELECT B.AUTHOR_ID AS AUTHOR_ID, B.AUTHOR_NAME AS AUTHOR_NAME, A.CATEGORY AS CATEGORY, (A.PRICE*SUM(C.SALES)) AS TOTAL_SALES 
FROM BOOK AS A, AUTHOR AS B, BOOK_SALES AS C 
WHERE A.AUTHOR_ID = B.AUTHOR_ID AND A.BOOK_ID = C.BOOK_ID AND DATE_FORMAT(C.SALES_DATE,"%Y-%m") = "2022-01"
GROUP BY C.BOOK_ID) AS A
GROUP BY A.AUTHOR_NAME,A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;