-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_INS AS A , ANIMAL_OUTS AS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID AND A.DATETIME>B.DATETIME 
ORDER BY A.DATETIME


# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS I, ANIMAL_OUTS O
# WHERE I.ANIMAL_ID=O.ANIMAL_ID AND I.DATETIME>O.DATETIME
# ORDER BY I.DATETIME;